### PR TITLE
Postfix parameter implementation

### PR DESCRIPTION
**Pull request by marciopamplona**
Configurable and optional postfix to rename the output.
Originally is hard-coded in "filename.min".

### CODE REVIEW

**Comment by olback** [comment]
Thanks for the PR! Before I merge this, I'm thinking that the same feature should be implemented for CSS.

**Comment by marciopamplona** [comment]
> Thanks for the PR! Before I merge this, I'm thinking that the same feature should be implemented for CSS.

Sure!
I made a commit:

[https://github.com/olback/es6-css-minify/pull/51/commits/ea61c68ccefe867658c6e9ba61b37c0de87c00b5](url)

**Comment by olback** [comment]
This will be published in a few hours.

**Comment by olback** [comment]
Version 2.2.0 pushed to the marketplace.

**Pull request closed without merging**
